# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pycodestyle pytest
        python -m pip install --prefer-binary .  # Test installation correctness
        python -m pip install .[dev,vis]  # Test extra dependencies
    - name: Lint with pycodestyle and mypy
      run: |
        pycodestyle . --count
        mypy --ignore-missing-imports --check-untyped-defs telluric/
    - name: Test with pytest
      run: |
        pytest -vv
    - name: Coverage
      run: |
        python -m pip uninstall telluric -y
        python -m pip install --editable .
        pytest --cov
        python -m pip install codecov
        codecov
